### ISSUE TITLE
License

### ISSUE THREAD

**Issue by arskanov** [danielcft/nordea-ynab-converter-dk#1]
Hi Daniel,

Could you specify a license under which the code in this repository is distributed? I'm interested in basing part of the Finnish Nordea - YNAB conversion off of your converter.

Thanks!

**Comment by danielcft** [comment]
Hi Artturi.
The license is MIT, and you are more than welcome to use it as a base for the Finish version.

The project is deprecated because the .csv files generated by the bank proved to be unreliable in terms of tokenizing/encoding/eof.
So I went ahead and made a firefox plugin that allows you to **directly** select transactions from the bank's website, right click and and export them as csv. The advantage is that it potentially works for any bank, independently of their export format.

 You are welcome to contribute with a pull request for the finnish version of this project (or create your own if you will). 

You can find the repository at https://github.com/danielcft/ynab-export-csv-extension

**Comment by arskanov** [comment]
Ok, thanks! Had a look at the new project, and it looks like it would work well for the Finnish desktop bank as well. I'm looking for a way that would work for mobile use too, so I'll be sticking with downloading the CSV for now. I haven't yet had issues with the format of NordeaFI:s exports, but they seem to be exported completely differently (i.e. tab seperator)

I'll be including modified parts of your code into a project with a mini web-server and use of the YNAB api. I wish the Nordea android app had export capability.
